FROM node:lts-alpine@sha256:2c405ed42fc0fd6aacbe5730042640450e5ec030bada7617beac88f742b6997b AS build

WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm ci --only=production

# See: docker inspect node:lts-alpine | jq -r ".[0].RepoDigests[0]" 
FROM node:lts-alpine@sha256:2c405ed42fc0fd6aacbe5730042640450e5ec030bada7617beac88f742b6997b

RUN apk add dumb-init

ENV NODE_ENV production
EXPOSE 3000

USER node
WORKDIR /usr/src/app
COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY --chown=node:node . /usr/src/app

CMD ["dumb-init", "node", "server.js"]
